"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Button, EmptyState, Field, LoadingState, Notice, PageHeader, Panel, TableWrap } from "@/components/ui";
import { ApiError, apiRequest, type ApiEnvelope } from "@/lib/api-client";
import { formatDate } from "@/lib/format";

type Office = { id: string; name: string; latitude: number; longitude: number; radius_m: number; active: boolean };
type Policy = { id: string; effective_from: string; effective_to: string | null; start_time: string; lunch_start: string; lunch_end: string; end_time: string; working_weekdays: number[]; late_grace_minutes: number; photo_retention_days: number };
type Holiday = { id: string; holiday_date: string; name: string; is_working_override: boolean };
type LeaveType = { id: string; code: string; name: string; deducts_annual_balance: boolean; active: boolean };
type SettingsData = { office_locations: Office[]; work_policies: Policy[]; holidays: Holiday[]; leave_types: LeaveType[] };
const weekdays = [{ value: 1, label: "Thứ 2" }, { value: 2, label: "Thứ 3" }, { value: 3, label: "Thứ 4" }, { value: 4, label: "Thứ 5" }, { value: 5, label: "Thứ 6" }, { value: 6, label: "Thứ 7" }, { value: 7, label: "Chủ nhật" }];

export default function AdminSettingsPage() {
  const [data, setData] = useState<SettingsData>({ office_locations: [], work_policies: [], holidays: [], leave_types: [] }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [office, setOffice] = useState({ name: "Văn phòng chính", latitude: "", longitude: "", radius_m: "100" });
  const [policy, setPolicy] = useState({ effective_from: new Date().toISOString().slice(0, 10), start_time: "08:00", lunch_start: "12:00", lunch_end: "13:00", end_time: "17:00", late_grace_minutes: "0", photo_retention_days: "90" });
  const [days, setDays] = useState<number[]>([1, 2, 3, 4, 5, 6]); const [holiday, setHoliday] = useState({ holiday_date: "", name: "", is_working_override: false }); const [leaveType, setLeaveType] = useState({ code: "", name: "", deducts_annual_balance: true });
  const [preview, setPreview] = useState(false);
  const validTimes = policy.start_time < policy.lunch_start && policy.lunch_start < policy.lunch_end && policy.lunch_end < policy.end_time;
  const minutes = (time: string) => Number(time.slice(0, 2)) * 60 + Number(time.slice(3, 5));
  const workMinutes = minutes(policy.lunch_start) - minutes(policy.start_time) + minutes(policy.end_time) - minutes(policy.lunch_end);
  const load = useCallback(async () => { try { const result = await apiRequest<ApiEnvelope<SettingsData>>("/api/v1/admin/settings"); setError(""); setData(result.data); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Không tải được cấu hình."); } finally { setLoading(false); } }, []);
  useEffect(() => {
    let active = true;
    apiRequest<ApiEnvelope<SettingsData>>("/api/v1/admin/settings")
      .then(result => { if (active) { setError(""); setData(result.data); } })
      .catch((cause: unknown) => { if (active) setError(cause instanceof ApiError ? cause.message : "Không tải được cấu hình."); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);
  async function save(path: string, body: unknown) { setSaving(true); setError(""); setMessage(""); try { await apiRequest(path, { method: "POST", body: JSON.stringify(body) }); setMessage("Đã lưu cấu hình."); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Không lưu được cấu hình."); } finally { setSaving(false); } }
  async function patch(path: string, body: unknown) { setSaving(true); setError(""); setMessage(""); try { await apiRequest(path, { method: "PATCH", body: JSON.stringify(body) }); setMessage("Đã cập nhật cấu hình."); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Không cập nhật được cấu hình."); } finally { setSaving(false); } }
  async function saveOffice(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const existing = data.office_locations.find(item => item.active); const body = { name: office.name.trim(), latitude: Number(office.latitude), longitude: Number(office.longitude), radius_m: Number(office.radius_m) }; if (!Number.isFinite(body.latitude) || !Number.isFinite(body.longitude)) { setError("Nhập tọa độ latitude và longitude hợp lệ."); return; } if (existing) await patch("/api/v1/admin/settings/office-locations/" + existing.id, body); else await save("/api/v1/admin/settings/office-locations", body); }
  async function savePolicy(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!validTimes) { setError("Giờ vào, bắt đầu nghỉ, kết thúc nghỉ và giờ ra phải tăng dần."); return; } if (!preview) { setPreview(true); return; } await save("/api/v1/admin/settings/work-policies", { ...policy, effective_to: null, working_weekdays: days, late_grace_minutes: Number(policy.late_grace_minutes), photo_retention_days: 90 }); setPreview(false); }
  async function saveHoliday(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await save("/api/v1/admin/settings/holidays", holiday); setHoliday({ holiday_date: "", name: "", is_working_override: false }); }
  async function saveLeaveType(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await save("/api/v1/admin/settings/leave-types", { ...leaveType, active: true }); setLeaveType({ code: "", name: "", deducts_annual_balance: true }); }
  function toggleDay(value: number) { setDays(current => current.includes(value) ? current.filter(day => day !== value) : [...current, value].sort()); }
  return <>
    <PageHeader title="Cấu hình hệ thống" description="Lịch nghỉ và tọa độ văn phòng chỉ hỗ trợ tính công, không cản chấm công. Ảnh bằng chứng mặc định giữ 90 ngày." action={<Button type="button" variant="secondary" onClick={() => void load()} disabled={loading}>Làm mới</Button>} />
    {error && <Notice kind="error">{error}</Notice>}{message && <Notice kind="success">{message}</Notice>}{loading && <LoadingState />}
    <Panel title="Văn phòng tham khảo" description="Tọa độ dùng để gắn cờ khoảng cách nếu người dùng chia sẻ GPS. Thiếu tọa độ không ngăn chấm công.">
      <form className="form-grid" onSubmit={saveOffice}><Field label="Tên địa điểm"><input required minLength={2} value={office.name} onChange={e => setOffice({ ...office, name: e.target.value })} /></Field><Field label="Latitude"><input required type="number" step="any" min="-90" max="90" value={office.latitude} onChange={e => setOffice({ ...office, latitude: e.target.value })} /></Field><Field label="Longitude"><input required type="number" step="any" min="-180" max="180" value={office.longitude} onChange={e => setOffice({ ...office, longitude: e.target.value })} /></Field><Field label="Bán kính tham khảo (m)"><input required type="number" min="10" max="50000" value={office.radius_m} onChange={e => setOffice({ ...office, radius_m: e.target.value })} /></Field><div className="form-actions"><Button type="submit" disabled={saving}>{data.office_locations.some(item => item.active) ? "Cập nhật văn phòng" : "Thêm văn phòng"}</Button></div></form>
      <div className="setting-list">{data.office_locations.map(item => <div className="setting-row" key={item.id}><span><strong>{item.name}</strong><small>{item.latitude}, {item.longitude} · bán kính {item.radius_m} m</small></span><span>{item.active ? "Đang hoạt động" : "Đã tắt"}</span></div>)}</div>
    </Panel>
    <Panel title="Chính sách giờ làm" description="Tạo phiên bản mới theo ngày hiệu lực; lịch chuẩn 08:00–12:00, 13:00–17:00 và thứ 2–thứ 7.">
      <form className="form-grid" onSubmit={savePolicy} onChange={() => setPreview(false)}><Field label="Hiệu lực từ"><input required type="date" value={policy.effective_from} onChange={e => setPolicy({ ...policy, effective_from: e.target.value })} /></Field><Field label="Bắt đầu"><input required type="time" value={policy.start_time} onChange={e => setPolicy({ ...policy, start_time: e.target.value })} /></Field><Field label="Bắt đầu nghỉ trưa"><input required type="time" value={policy.lunch_start} onChange={e => setPolicy({ ...policy, lunch_start: e.target.value })} /></Field><Field label="Kết thúc nghỉ trưa"><input required type="time" value={policy.lunch_end} onChange={e => setPolicy({ ...policy, lunch_end: e.target.value })} /></Field><Field label="Kết thúc"><input required type="time" value={policy.end_time} onChange={e => setPolicy({ ...policy, end_time: e.target.value })} /></Field><Field label="Ân hạn đi trễ (phút)"><input required type="number" min="0" max="240" value={policy.late_grace_minutes} onChange={e => setPolicy({ ...policy, late_grace_minutes: e.target.value })} /></Field><Field label="Lưu ảnh"><input readOnly value="3 tháng từ lúc tải ảnh" /></Field><div className="field full"><span>Ngày làm việc</span><div className="checklist">{weekdays.map(day => <label className="check-item" key={day.value}><input type="checkbox" checked={days.includes(day.value)} onChange={() => toggleDay(day.value)} />{day.label}</label>)}</div></div><div className="form-actions full">{preview && <Notice>Toàn bộ nhân viên áp dụng từ {formatDate(policy.effective_from)}: {policy.start_time}–{policy.end_time}, nghỉ {policy.lunch_start}–{policy.lunch_end}, {workMinutes} phút/ngày, miễn trừ trễ {policy.late_grace_minutes} phút. Phiên bản trước kết thúc vào ngày liền trước; snapshot kỳ đã khóa giữ nguyên.</Notice>}<Button type="submit" disabled={saving || days.length === 0 || !validTimes}>{preview ? "Xác nhận lưu phiên bản" : "Xem trước thay đổi"}</Button></div></form>
      {data.work_policies.length > 0 && <TableWrap><table><thead><tr><th>Hiệu lực</th><th>Lịch</th><th>Ân hạn</th><th>Lưu ảnh</th></tr></thead><tbody>{data.work_policies.map(item => <tr key={item.id}><td data-label="Hiệu lực">{formatDate(item.effective_from)}{item.effective_to ? " – " + formatDate(item.effective_to) : " – hiện hành"}</td><td data-label="Lịch">{item.start_time.slice(0, 5)}–{item.lunch_start.slice(0, 5)} · {item.lunch_end.slice(0, 5)}–{item.end_time.slice(0, 5)}<small>{item.working_weekdays.map(value => weekdays.find(day => day.value === value)?.label).join(", ")}</small></td><td data-label="Ân hạn">{item.late_grace_minutes} phút</td><td data-label="Lưu ảnh">3 tháng</td></tr>)}</tbody></table></TableWrap>}
    </Panel>
    <div className="settings-two-column">
      <Panel title="Lịch nghỉ / làm bù" description="Ngày làm bù được tính như ngày làm việc; ngày nghỉ vẫn cho phép ghi nhận công.">
        <form className="form-grid" onSubmit={saveHoliday}><Field label="Ngày"><input required type="date" value={holiday.holiday_date} onChange={e => setHoliday({ ...holiday, holiday_date: e.target.value })} /></Field><Field label="Tên ngày"><input required minLength={2} maxLength={160} value={holiday.name} onChange={e => setHoliday({ ...holiday, name: e.target.value })} /></Field><Field label="Quy tắc ngày"><select value={String(holiday.is_working_override)} onChange={e => setHoliday({ ...holiday, is_working_override: e.target.value === "true" })}><option value="false">Ngày nghỉ</option><option value="true">Ngày làm bù</option></select></Field><div className="form-actions"><Button type="submit" disabled={saving}>Thêm lịch</Button></div></form>
        {data.holidays.length === 0 ? <EmptyState title="Chưa có lịch đặc biệt" /> : <div className="setting-list">{data.holidays.map(item => <div className="setting-row" key={item.id}><span><strong>{formatDate(item.holiday_date)} · {item.name}</strong><small>{item.is_working_override ? "Ngày làm bù" : "Ngày nghỉ"}</small></span><Button type="button" variant="secondary" disabled={saving} onClick={() => void patch("/api/v1/admin/settings/holidays/" + item.id, { is_working_override: !item.is_working_override })}>{item.is_working_override ? "Đổi thành ngày nghỉ" : "Đổi thành ngày làm"}</Button></div>)}</div>}
      </Panel>
      <Panel title="Loại nghỉ phép" description="Loại phép và phép năm được ghi nhận qua sổ phép, không nhập số dư trực tiếp tại đây.">
        <form className="form-grid" onSubmit={saveLeaveType}><Field label="Mã loại nghỉ"><input required minLength={2} maxLength={30} pattern="[A-Za-z0-9_-]+" value={leaveType.code} onChange={e => setLeaveType({ ...leaveType, code: e.target.value })} /></Field><Field label="Tên loại nghỉ"><input required minLength={2} maxLength={120} value={leaveType.name} onChange={e => setLeaveType({ ...leaveType, name: e.target.value })} /></Field><label className="check-item full"><input type="checkbox" checked={leaveType.deducts_annual_balance} onChange={e => setLeaveType({ ...leaveType, deducts_annual_balance: e.target.checked })} /> Trừ vào số dư phép năm</label><div className="form-actions full"><Button type="submit" disabled={saving}>Thêm loại nghỉ</Button></div></form>
        {data.leave_types.length === 0 ? <EmptyState title="Chưa có loại nghỉ" /> : <div className="setting-list">{data.leave_types.map(item => <div className="setting-row" key={item.id}><span><strong>{item.name}</strong><small>{item.code} · {item.deducts_annual_balance ? "trừ phép năm" : "không trừ phép năm"} · {item.active ? "đang dùng" : "đã tắt"}</small></span><Button type="button" variant="secondary" disabled={saving} onClick={() => void patch("/api/v1/admin/settings/leave-types/" + item.id, { active: !item.active })}>{item.active ? "Tắt" : "Bật"}</Button></div>)}</div>}
      </Panel>
    </div>
  </>;
}
